python run_clm.py \
    --model_name_or_path gpt2-small \
    --train_file "data/nela-covid-2020-train.json" \
    --validation_file "data/nela-covid-2020-valid.json" \
    --do_train \
    --do_eval \
    --logging_first_step \
    --output_dir "outputs/gpt2-sm-covid" \
    --per_device_train_batch_size 4 \
    --per_device_eval_batch_size 4 \
    --save_total_limit 1 \
    --evaluation_strategy steps \
    --logging_steps 10000 \
    --save_steps 10000 \
    --eval_steps 10000 \
    --block_size 500 \
    --overwrite_output_dir \
    --fp16 \
